name: calculate_plugin
description: A Flutter plugin for financial calculations.
version: 0.0.1
homepage: https://github.com/Kamalhossain24/sip-calculate-dart
repository: https://github.com/Kamalhossain24/sip-calculate-dart
issue_tracker: https://github.com/Kamalhossain24/sip-calculate-dart/issues
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# Remove platform-specific plugin configurations
flutter:
  plugin:
    implements: flutter