name: calculate_plugin
description: A Flutter plugin for financial calculations.
version: 0.0.1
homepage: https://github.com/Kamalhossain24/sip-calculate-plugin
repository: https://github.com/Kamalhossain24/sip-calculate-plugin
issue_tracker: https://github.com/Kamalhossain24/sip-calculate-plugin/issues
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.calculate_plugin
      ios:
        pluginClass: CalculatePlugin
